version: "3.8"

services:
  postgres:
    image: 'postgres:16.2-alpine3.19'
    container_name: 'postgres-db'
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=service_dev
    ports:
      - 54333:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PORT_NUMBER=7000
      - REDIS_PASSWORD=redis
    volumes:
      - redis_data:/data
    ports:
      - '7000:7000'

volumes:
  postgresdata:
  redis_data:


