export const EMAIL_WAS_EXIST = 'EMAIL_WAS_EXIST';
export const OFFER_WAS_EXIST = 'OFFER_WAS_EXIST';
export const PURCHASE_WAS_EXIST = 'PURCHASE_WAS_EXIST';
export const NOT_FOUND_USER = 'NOT_FOUND_USER';
export const NOT_FOUND_OFFER = 'NOT_FOUND_OFFER';
